### ISSUE TITLE
demo (rsv) page not found

### ISSUE THREAD

**Issue by howywowy** [benkeen/rsv#6]
Hi,

I am a rooky on github, so maybe this is off topic, but I do not know how else to conatct you. The demo page seems to be off line. 

http://www.benjaminkeen.com/open-source-projects/smaller-projects/really-simple-validation-js/really-simple-validation-standalone-version/experiments/rsv/standalone/

**Comment by benkeen** [comment]
Oops, looks like a dud link. I'll update it in a sec. Here's the correct URL:
http://www.benjaminkeen.com/open-source-projects/smaller-projects/really-simple-validation-js/really-simple-validation-standalone-version/
